org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.74
neo_version_range=[26.1.2.74,26.1.3)
ae2_version=26.1.10-beta

mod_id=observable
mod_name=Observable - Remake
mod_license=MPL-2.0
mod_version=1.0.1
artifact_name=Observable-Remake-V1.0.1-NeoForge-26.1.2.74
mod_group_id=de.bomberbude.observable.remake
kotlin.compiler.execution.strategy=in-process
org.gradle.workers.max=4
